name: AppWright Test
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install CLI and backend dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install fastapi uvicorn pydantic

      - name: Start backend service
        run: |
          nohup python -c "import uvicorn; uvicorn.run('job_server.main:app', host='127.0.0.1', port=8000)" &
          sleep 5

      - name: Submit test job
        id: submit
        run: |
          qgjob submit --org-id=qualgent --app-version-id=xyz123 --test=tests/onboarding.spec.js --target=emulator

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AppWright
        run: npm install -g appwright

      - name: Install Playwright
        run: npm install -g playwright

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run AppWright test
        run: npx appwright test tests/onboarding.spec.js 